### ISSUE TITLE
Meandering feedback

### ISSUE THREAD

**Issue by elucid** [PrecisionNutrition/active_jorb#19]
I'm just trying to read through this and make sense of things. I have some questions and will use this issue as a place to have a discussion.

**Comment by elucid** [comment]
I'm curious why https://github.com/PrecisionNutrition/active_jorb/blob/master/lib/active_jorb/job.ex#L22-L27 doesn't include `executions` or `job_id`. Since we are only concerned with enqueueing, could we not just always enqueue with `executions: 0`? Similarly, since Rails just uses v4 UUIDs for job_ids, could we not generate those also for enqueueing? Is there any downside to enqueueing jobs without `job_id`s (e.g. ActiveJob wouldn't log the job id on execution and so would make troubleshooting a broken/stuck job difficult).

**Comment by elucid** [comment]
I don't think that https://github.com/PrecisionNutrition/active_jorb/blob/master/lib/active_jorb/job.ex#L17 is part of the ActiveJob API. I think it's a Sidekiq thing only.

**Comment by elucid** [comment]
https://github.com/PrecisionNutrition/active_jorb/blob/master/lib/active_jorb/job.ex#L22-L27 is also missing `provider_job_id` which will be would provided by Sidekiq

**Comment by elucid** [comment]
What does https://github.com/PrecisionNutrition/active_jorb/blob/3ef5ae6466d290e74b99db074ee9bd048844f65e/lib/active_jorb/queue_adapter/sidekiq.ex#L56 do?

**Comment by elucid** [comment]
See also https://github.com/PrecisionNutrition/active_jorb/blob/3ef5ae6466d290e74b99db074ee9bd048844f65e/lib/active_jorb/queue_adapter/sidekiq.ex#L28 re: retries.

I think the issue here is that Sidekiq and ActiveJob have completely separate retry mechanisms. ActiveJob doesn't integrate with Sidekiq's retry mechanism, it only relies on the ability to schedule jobs in the future, and managed the scheduling of those retries rather than relying on Sidekiq to do it. IMO from ActiveJorb's perspective, this should always be supplied as `retry: false`.

**Comment by jherdman** [comment]
> I'm curious why https://github.com/PrecisionNutrition/active_jorb/blob/master/lib/active_jorb/job.ex#L22-L27 doesn't include executions or job_id [ snip snip snip ] is also missing provider_job_id which will be would provided by Sidekiq ...

* Executions should definitely be included, that's an oversight on my part.
* `job_id` is definitely also an oversight. I can add that in too.
* [`provider_job_id`](https://github.com/rails/rails/blob/b7760eb75a9dd002260a361119aea0b255e1f573/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L22-L27) is an interesting beast. It is the [_true_ job ID provided by Sidekiq](https://github.com/mperham/sidekiq/wiki/Active-Job#job-id). This value is generated when, in our case, we hand off the normalized job to Sidewalk to write to Redis. As such we never get this value until the job is in [the enqueue pipeline](https://github.com/railsmechanic/sidewalk/blob/1e3fa28bf0c94f245a9bb2cd94c11cc62fc3c509/lib/sidewalk/client.ex#L28) (see also [#normalize_job](https://github.com/railsmechanic/sidewalk/blob/1e3fa28bf0c94f245a9bb2cd94c11cc62fc3c509/lib/sidewalk/client.ex#L86)). Luckily this value is only ever used if you want access to the real Sidekiq job, which is something we needn't necessarily support.

**Comment by jherdman** [comment]
> What does `ts / 1` do?

This converts the number to a float:

```elixir
iex(1)> 20 / 1
20.0
```

**Comment by elucid** [comment]
Hmm. Maybe `.to_f` would communicate this better?

**Comment by jherdman** [comment]
Released as 0.1.2.
